version: '3'

services:
  bots-complete:
    build:
      context: .
      dockerfile: ./compose/bots_complete/Dockerfile
    ports:
      - "0.0.0.0:8080:8080"
      - "0.0.0.0:9001:9001"
    env_file:
      - .env
    volumes:
      - ./src/bots/usersys:/usr/local/lib/python2.7/dist-packages/bots/usersys
    command: /bots/compose/bots_complete/docker-entrypoint.sh